FROM golang:1.18.8-alpine3.16

ARG TARGETOS
ARG TARGETARCH

WORKDIR /home/app/gopractise
 
COPY  ./go.* .

RUN go mod download

COPY . .

RUN GOOS=${TARGETOS} GOARCH=${TARGETARCH} go build .

CMD ["./gopractise"]